stages:
  - deploy

deploy-image:
  stage: deploy
  script:
    - docker login -u "${HUB_REGISTRY_USERNAME}" -p "${HUB_REGISTRY_PASSWORD}"
    - docker build -t "${HUB_REGISTRY_IMAGE}:latest" containers/danbooru
    - export DANBOORU_REVISION="$(docker run --rm "${HUB_REGISTRY_IMAGE}:latest" cat /REVISION)"
    - docker tag "${HUB_REGISTRY_IMAGE}:latest" "${HUB_REGISTRY_IMAGE}:${DANBOORU_REVISION}"
    - docker push "${HUB_REGISTRY_IMAGE}:latest" "${HUB_REGISTRY_IMAGE}:${DANBOORU_REVISION}"
    - docker images "${HUB_REGISTRY_IMAGE}:${DANBOORU_REVISION}"
    - docker history "${HUB_REGISTRY_IMAGE}:${DANBOORU_REVISION}"
    - docker rmi "${HUB_REGISTRY_IMAGE}:latest" "${HUB_REGISTRY_IMAGE}:${DANBOORU_REVISION}"
  only:
    - master
    - tags
    - branches
  tags:
    - docker-deploy
