version: '2'

services:
  danbooru:
    build:
      context: ./containers/danbooru
    ports:
      - 8080:8080
    environment:
      - RAILS_ENV=production
      - NEWRELIC_AGENT_ENABLED=false

      - POSTGRES_USERNAME=danbooru
      - POSTGRES_PASSWORD=foobarXYZ123
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=danbooru2

      - SERVER_NAME=docker.lan

      - DANBOORU_MEMCACHED_SERVERS=memcached:11211

      # openssl rand -hex 32 > ~/.danbooru/secret_token
      # openssl rand -hex 32 > ~/.danbooru/session_secret_key
      - SECRET_TOKEN=${SECRET_TOKEN}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}

      - DANBOORU_PASSWORD_SALT=${DANBOORU_PASSWORD_SALT}
      - DANBOORU_EMAIL_KEY=${DANBOORU_EMAIL_KEY}

      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    volumes:
      - danbooru-data:/var/www/danbooru2/shared/public/data

      - ./config/danbooru_local_config.rb:/var/www/danbooru2/shared/config/danbooru_local_config.rb:ro

      - ./containers/danbooru/container/etc/cont-init.d:/etc/cont-init.d:ro
      - ./containers/danbooru/container/etc/services.d:/etc/services.d:ro

      - ./containers/danbooru/container/var/www/templates:/var/www/templates:ro
      - ./containers/danbooru/container/var/www/danbooru2/shared/config.ru:/var/www/danbooru2/shared/config.ru:ro

      - ./containers/danbooru/container/var/www/danbooru2/shared/config/unicorn/production.rb:/var/www/danbooru2/shared/config/unicorn/production.rb:ro
      - ./containers/danbooru/container/var/www/danbooru2/shared/config/environments/production.rb:/var/www/danbooru2/shared/config/environments/production.rb:ro

  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: danbooru2
      POSTGRES_USER: danbooru
      POSTGRES_PASSWORD: foobarXYZ123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5-alpine

volumes:
  postgres-data:
  danbooru-data:
