version: '2'

services:
  moebooru:
    build:
      context: ./containers/dev
    working_dir: /var/www/danbooru2/shared
    ports:
      - 8080:8080
    environment:
      - RAILS_ENV=production
      - NEWRELIC_AGENT_ENABLED=false

      - POSTGRES_USERNAME=danbooru
      - POSTGRES_PASSWORD=foobarXYZ123
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_DATABASE=danbooru2

      - SERVER_NAME=docker.lan

      - SECRET_TOKEN=5902091a0f8e31ceca499b6d5f39dd10f7f97c5bd457b3a08ee55638e2b0df10
      - SESSION_SECRET_KEY=941b5047ef21df82fca8812eef18cbe29580956d5e123a750c4d911164fb8f9f
    volumes:
      - danbooru-data:/var/www/danbooru2/shared/public/data

      - ./config/danbooru_local_config.rb:/var/www/danbooru2/shared/config/danbooru_local_config.rb:ro
      # - ./config/env.sh:/var/www/danbooru2/shared/.env.production

      - ./container/etc/cont-init.d:/etc/cont-init.d:ro
      - ./container/etc/services.d:/etc/services.d:ro

      - ./container/var/www/templates:/var/www/templates:ro
      - ./container/var/www/danbooru2/shared/config.ru:/var/www/danbooru2/shared/config.ru:ro

      - ./container/var/www/danbooru2/shared/config/unicorn/production.rb:/var/www/danbooru2/shared/config/unicorn/production.rb:ro
      - ./container/var/www/danbooru2/shared/config/environments/production.rb:/var/www/danbooru2/shared/config/environments/production.rb:ro

  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: danbooru2
      POSTGRES_USER: danbooru
      POSTGRES_PASSWORD: foobarXYZ123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5-alpine

volumes:
  postgres-data:
  danbooru-data:
